actinspace/actinspace/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('inicio.urls', 'inicio'), namespace='inicio')),
]

actinspace/inicio/urls.py
from django.contrib import admin
from django.urls import include, path
from inicio.views import inicio
urlpatterns = [
    path('', inicio.as_view(), name='inicio')
]

actinspace/inicio/models.py
from django.db import models

# Create your models here.

actinspace/persona/models.py
from django.db import models
# Create your models here.
class Persona(models.Model):
    nombrePersona = models.CharField(max_length=200)
    apellidoPersona = models.CharField(max_length=200)
    codgps = models.CharField(max_length=300)


    def __str__(self):
        return '{}'.format(self.nombrePersona)
    def save(self):
        self.nombrePersona = self.nombrePersona
        self.apellidoPersona = self.apellidoPersona
        self.codgps = self.codgps


class Meta:
    verbose_name_plural = 'Personas'

actinspace/inicio/views.py
from django.shortcuts import render
from django.views import generic
from django.http import HttpResponse
class inicio(generic.TemplateView):  
    template_name = "inicio.html"
   

actinspace/persona/views.py
from django.shortcuts import render

# Create your views here.

actinspace/inicio/templates/inicio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet"
        crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous">
    </script>

</head>

<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'inicio:inicio' %}">Geo-match</a><button
            class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i
                class="fas fa-bars"></i></button><!-- Navbar Search-->
 
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto mr-0 mr-md-3 my-2 my-md-0 ">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                 
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        
                        
                        <div class="sb-sidenav-menu-heading">Navegacion</div>
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts"
                            aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            formularios
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne"
                            data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                   
                            </nav>
                        </div>
                       
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo"
                            data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-toggle="collapse"
                                    data-target="#pagesCollapseAuth" aria-expanded="false"
                                    aria-controls="pagesCollapseAuth">Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div></a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne"
                                    data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link"
                                            href="login.html">Login</a><a class="nav-link"
                                            href="register.html">Register</a><a class="nav-link"
                                            href="password.html">Forgot Password</a></nav>
                                </div>
                                <a class="nav-link collapsed" href="#" data-toggle="collapse"
                                    data-target="#pagesCollapseError" aria-expanded="false"
                                    aria-controls="pagesCollapseError">Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div></a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne"
                                    data-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav"><a class="nav-link" href="401.html">401
                                            Page</a><a class="nav-link" href="404.html">404 Page</a><a class="nav-link"
                                            href="500.html">500 Page</a></nav>
                                </div>
                            </nav>
                        </div>
                       
                      
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small"></div>
                    UTADEO
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    {% block contenido %}
                    <br>
          
                            
                    {% endblock contenido %}

                </div>

            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2019</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous">
    </script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="{% static 'assets/demo/datatables-demo.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"crossorigin="anonymous"></script>
        <script>
            $(document).ready(function () {
                $('#elminarModal').modal({backdrop: 'static', keyboard: false});
                $('#elminarModal').modal('show')
                string2=sessionStorage['precio']
                $('#id_usuario').val(string2)
                $( "#fondop" ).load("/Persona/loadPersona");
                $( "#fondou" ).load("/Usuario/loadusuario");
                $( "#fondotc" ).load("/Tiposcasos/tiposcaso");
                $( "#fondoc" ).load("/Caso/loadcaso");
                $(function () {
                    $('[data-toggle="popover"]').popover()
                })
            });   
        </script>
</body>
</html>